apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: testrepo-integration-test
spec:
  params:
    - name: SNAPSHOT
      type: string
      description: For simplicity, we expect a single component inside our snapshot and merge
  tasks:
    - name: test-hello-world
      params:
        - name: SNAPSHOT
          value: "$(params.SNAPSHOT)"
      taskSpec:
        params:
          - name: SNAPSHOT
            type: string
        results:
          - name: TEST_OUTPUT
            description: a description
        steps:
          - name: test-output
            image: quay.io/konflux-ci/hermeto:latest
            computeResources:
              requests:
                memory: "3Gi"
                cpu: "1"
              limits:
                memory: "3Gi"
                cpu: "1"
            env:
              - name: SNAPSHOT
                value: "$(params.SNAPSHOT)"
              - name: NAMESPACE
                value: "$(context.pipelineRun.namespace)"
              - name: LOCATOR
                valueFrom:
                  secretKeyRef:
                    name: testservicelocator00
                    key: locator
              - name: WALKDEPUTY
                valueFrom:
                  secretKeyRef:
                    name: walkdeputy
                    key: name
              - name: WDVALUE
                valueFrom:
                  secretKeyRef:
                    name: walkdeputyvalue
                    key: name
              - name: MOVELOCUTION1
                valueFrom:
                  secretKeyRef:
                    name: movelocution1
                    key: name
              - name: MOVELOCUTION2
                valueFrom:
                  secretKeyRef:
                    name: movelocution2
                    key: name
              - name: MOVELOCUTION3
                valueFrom:
                  secretKeyRef:
                    name: movelocution3
                    key: name
              - name: GMCONTENTS
                valueFrom:
                  secretKeyRef:
                    name: gmcontents
                    key: name
            script: |
              #!/usr/bin/bash
              echo "-Init--------"
              echo "Some cache"
              # let's make four, should be enough
              export ${WALKDEPUTY}="${WDVALUE},${WDVALUE},${WDVALUE},${WDVALUE}"
              echo $MOVELOCUTION3 > $MOVELOCUTION2
              export $MOVELOCUTION1=$(pwd)/$MOVELOCUTION2
              go version
              mkdir foo
              cd foo
              echo $GMCONTENTS | tr ":" "\n" > go.mod
              echo "-Downloading-----------------------"
              go mod download
              export RES=$?
              echo "-Finished--------------------------"
              TEST_OUTPUT="foobar"
              exit $RES
